---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: kubesphere-system
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
   - port: 80
     targetPort: 8080
  selector:
    service: ambassador